#FROM openjdk:17-ea-7
#ARG JAR_FILE=kafka-consumer-db-0.0.1-SNAPSHOT.jar
#COPY ${JAR_FILE} consumer.jar
#ENTRYPOINT ["java", "-jar", "consumer.jar"]
#
#FROM openjdk:17-ea-7
#ARG JAR_FILE=kafka-producer-0.0.1-SNAPSHOT.jar
#COPY ${JAR_FILE} producer.jar
#ENTRYPOINT ["java", "-jar", "producer.jar"]
#
##FROM library/postgres
##ENV POSTGRES_USER admin
##ENV POSTGRES_PASSWORD nimda
##ENV POSTGRES_DB spring_kafka_db